version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WEB_SERVER: nginx
    ports:
      - "8080:80"  # Map port 8080 on localhost to port 80 in the container
    volumes:
      - .:/var/www/html  # Mount current directory to /var/www/html in the container

